#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

## {{ Set up error handler.
if [ "$(type -t errorhandlergeneral)" = "function" ]; then
   ## Function errorhandlergeneral exists (declared in
   ## help-steps/pre). Prefer to use the more feature rich version of the error
   ## handler.
   trap "errorhandlergeneral" ERR
else
   ## Function errorhandlergeneral does not exist. Script
   ## runs standalone outside the build script. Fall back to a simpler error
   ## handler.
   trap "error_handler" ERR
fi
## }}

own_filename="$(basename "$BASH_SOURCE")"
for skip_script in $SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      true "INFO: Skipping $own_filename, because SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

true "INFO: Running \"vrms\", as a sanity test, to check if packages from the contrib or non-free APT repository have been accidentally installed."
## For visible output, debugging.
vrms

## For machine readable output, taking action depending on.
vrms_result="$(vrms --quiet --sparse)"

vrms_expected_result_one="
virtualbox-guest-utils
virtualbox-guest-x11"

vrms_expected_result_two='
virtualbox-guest-dkms
virtualbox-guest-utils
virtualbox-guest-x11'

if [ "$vrms_result" = "" ]; then
   true "INFO $BASH_SOURCE: No non-free or contrib packages detected."
elif [ "$vrms_result" = "$vrms_expected_result_one" ]; then
   true "INFO $BASH_SOURCE: Only expected contrib packages detected."
elif [ "$vrms_result" = "$vrms_expected_result_two" ]; then
   true "INFO $BASH_SOURCE: Only expected contrib packages detected."
else
   if [ "$CI" = "true" ]; then
      true "INFO $BASH_SOURCE: Non-free or contrib packages detected. Continuing, because CI detected."
   else
      error "ERROR $BASH_SOURCE: Non-free or contrib packages detected! See above!"
   fi
fi

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
